version: '3.10'

services:
  bot:
    build: 
      context: ./bot/
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=api:8890
    depends_on:
      - api
    networks:
      - mynetwork

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.api
    ports:
      - "8890:8890"
    networks:
      - mynetwork

networks:
  mynetwork: {}
