# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /usr/src/bondarenko_bot

# Copy the current directory contents into the container at /usr/src/app
COPY /. /usr/src/bondarenko_bot

# Copy the bot's requirements file and install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the application
CMD ["python", "main.py"]